var GAME_LEVELS = [
  ["  x                                                                                        x ",
   "  x                                                                                        x ",
   "  x                               a                        a                               x ",
   "  x                                                                                        x ",
   "  x                                                                                        x ",
   "  x                              xxx                      xxx                              x ",
   "  x                              xxx                      xxx                              x ",
   "  x                            xx   xxx                xxx   xx                            x ",
   "  x                            xx   xxx                xxx   xx                            x ",
   "  x                            xx      xxxxxxxxxxxxxxxx      xx                            x ",
   "  x                            xx                            xx                            x ",
   "  x               a            xx                            xx           a                x ",
   "  x                          xx                                xx                          x ",
   "  x            xxxxxxx       xx       xxx              xxx     xx      xxxxxxx             x ",
   "  x          xx       xx     xx       xxx              xxx     xx    xx       xx           x ",
   "  x          xx       xx     xx               xxxxx            xx    xx       xx        o  x ",
   "  x  @       xxxxxxxxxxx     xx                 x              xx    xxxxxxxxxxx           x ",
   "  xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             "],
   ["  x                                                                                                                     ",
    "  x                                                                                                                     ",
    "  x     xxxxxx                          xxxxxx                    xxx                                                   ",
    "  x     !!    xx    xxxxxxxxxxxxxx    xx    !!                  xx   xx                                                 ",
    "  x     !!      xxxx              xxxx      !!                  xx   xx                                                 ",
    "  x     !!                                  !!                  xx   xx                                                 ",
    "  x       !!                              !!                    xx   xx                                                 ",
    "  x       !!                              !!                    xx   xx                                                 ",
    "  x     !!                                  !!                  xx   xx                                                 ",
    "  x   !!                                      !!                xx   xx                                                 ",
    "  x   !!                                  @   !!                xx   xx                                                 ",
    "  x   !!                                      !!                xx   xx                                                 ",
    "  x   !!                                      !!              xx     xx                                                 ",
    "  x   !!                               xxxxxxxxxxxxx          xx    xx                                                  ",
    "  x   !!                            xxx             !!!!!   xx      xx                                                  ",
    "  x   !!                          xx                    !!xx      xx                                                    ",
    "  x     xx                     xxx                      xx      xx                                                      ",
    "  x       xx                                          xx      xxxx                                                      ",
    "  x         xxxx       xxxx                                 xx   !!                                                     ",
    "  x             xxxxxxxx                            xx  xx       !!!!                                                   ",
    "  x                !!                                 !!           !!                                                   ",
    "  x                !!                               xx||xx         !!                                                   ",
    "  x                !!                                                                                                   ",
    "  x                !!                                                                                                   ",
    "  x                !!                                                                                                   ",
    "  x                  !!     xxxx                                 xx                                                     ",
    "  x                  !!     !!  xxxxxx     xxxxx        xxxx     !!                                                     ",
    "  x                  !!     !!      xx     !!   xxxxxx  xx       !!                                                     ",
    "  x                  !!     !!      !!     !!           !!     !!                                                       ",
    "  x                    !!   !!      !!     !!           !!     !!                                                       ",
    "  x                      !!!        !!     !!           !!   !!                                                         ",
    "  x                                 !!   !!               !!!                                            o              ",
    "  x                                   !!!                             a                                                 ",
    "  x                                        xxx                                                          xxx             ",
    "  x                                         xx                                    a                     xx              ",
    "  x                                         xx                        xx                                xx              ",
    "  x                                         xx     xx               xxxxxx                    xx        xx              ",
    "  x                                         xx    xxxx            xxxxxxxxxx     xxx         xxxx       xx              ",
    "  x                                         xx!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!xxxxxx!!!!!!xx              ",
    "  x                                         xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx              ",
    "  x                                         xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx              ",
    "  x                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
    "  x                                                                                                                     ",
    "  x                                                                                                                     ",
    "  x                                                                                                                     ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
    ["  x                                                                                                                                  ",
     "  x                                                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         ",
     "  x      !!!!!!!          !!!!!!!!!         !!!!!!!!!!        !!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                       ",
     "  x!!!!!!       !!!!!!!!!!         !!!!!!!!!          !!!!!!!!      xx!!!!             xx               !!!!xx                       ",
     "  x                                                                 xx!!                      a     xx    !!xx                       ",
     "  x                                                                 xx!!      xx                          !!xx                       ",
     "  x                                                                 xx!!                    xx            !!xx                       ",
     "  x                                                                 xx!!    a                             !!xx                       ",
     "  x                                                                 xx!!             xx     xxxx          !!xx  xxxx                ",
     "  x                                                                 xx!!                  xx    xx    o   !!xxxx    xx               ",
     "  x                                                                 xx!!    xx            xx      xx      !!xx      xx               ",
     "  x                                                                                       xx        xxxxxxxx        xx               ",
     "  x                                                                                 xx    xx                        xx               ",
     "  x                                                               xxxxxx                xx                            xx             ",
     "  x                                                   a         xx  xx!!    xx          xx      xx!!        xx!!      xx             ",
     "  x                                                          xxx    xx!!                xx      xxxx    xx  xxxx      xx             ",
     "  x                                                       xxxx   xxxxx!!     a    xx    xx  !!!!                !!!!  xx             ",
     "  x                                                   xxxx      xx  xx!!  xx            xx  !!!!  xx   xx   xx  !!!!  xx             ",
     "  x                                               xxxx     xxxxx    xx!!!!                xx      xxxxxxxxxxxx      xx               ",
     "  x                                             xx     xxxxx      xxxxxx!!!!!!!!!!!!!!!!!!!!xx                    xx                 ",
     "  x          @                                  xxxxxxx         xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
     "  x                          xxxxxxx       xxxxxxx       !!!!!!!xx    xxxx  xx    xx          xx    xx  xx    xx                     ",
     "!!!!!!!!!xxxxxxxxxxxxxxxxxxxx       !!!!!!!       !!!!!!!       xxxxxxxx    xxxxxx              xxxxxx    xxxx                       ",
     "                                                                                                                                     "],
     ["  x                                                                                        x ",
      "  x        x   x   x  xxxx  xxxx   xx   xxxx    x   x   x  xxxx  xxxx   xx   xxxx          x ",
      "  x        x   x   x  x  x  x  x  x  x  x       x   x   x  x  x  x  x  x  x  x             x ",
      "  x        x   x   x  x  x  x  x  xxxx  x       x   x   x  x  x  x  x  xxxx  x             x ",
      "  x        x x x   x  x  x  x  x  x     x       x x x   x  x  x  x  x  x     x             x ",
      "  x        xx xx   x  x  x  x  x  xxxx  x       xx xx   x  x  x  x  x  xxxx  x             x ",
      "  x                                                                                        x ",
      "  x    xxxx  x  x  x  xxxx  x  x   xx   xxxx     xxx   x  xxxx  xxxx   xx   xxxx    xx     x ",
      "  x    x     x  x  x  x     x x   x  x  x  x  @  x  x  x  x  x  x  x  x  x  x       xx     x ",
      "  x    x     xxxx  x  x     xx    xxxx  x  x     x  x  x  x  x  x  x  xxxx  x       xx     x ",
      "  x    x     x  x  x  x     x x   x     x  x     x  x  x  x  x  x  x  x     x              x ",
      "  x    xxxx  x  x  x  xxxx  x  x  xxxx  x  x     xxx   x  x  x  x  x  xxxx  x       xx     x ",
      "  x                                                                                        x ",
      "  x                                                                                        x ",
      "  x                                                                                        x ",
      "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
      "                                                                                             ",
      "                                                                                             "],
];

if (typeof module != "undefined" && module.exports)
 module.exports = GAME_LEVELS;
